// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// CLI-only config: migrate/introspect/studio run through here, so this uses
// the direct (unpooled) Neon connection — PgBouncer's pooled connection
// doesn't support the session-level operations these commands need.
// The running app never reads this file; it connects separately via the
// pooled DATABASE_URL through the @prisma/adapter-pg driver adapter (see lib/prisma.ts).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
